### ISSUE TITLE
spMagmaMan duplicates

### ISSUE THREAD

**Issue by BrendanMulcahy** [GET-TUDA-CHOPPA/SpelunkBots#4]
global.spMagmaMan = 29; ************
global.spTombLord = 30;
global.spOlmec = 31;
global.spCavemanWorship = 32;
global.spHawkmanWorship = 33;
global.spOlmecDebris = 34;
global.spSnake = 35;
global.spSpiderHang = 36;
global.spMagmaMan = 37; ************

Also, duplicated in stdafx.h

**Comment by Poliziano** [comment]
Hi BrendanMulcahy,

This duplication has been removed. Thank you for bring it to our attention.

Kind regards.
